version: "3.7"
networks:
    default:
        name: wikiforest
        driver: bridge
services:
    web:
        image: nginx:latest
        restart: always
        volumes:
            - ./deploy/nginx/templates:/etc/nginx/templates
            - ./deploy/nginx/logs:/web/logs/nginx
            - .:/opt/www
        expose:
            - 80
        environment:
            NGINX_PORT: ${DOCKER_WEB_PORT}
            DOCKER_UI_IP: ${DOCKER_UI_IP}
            DOCKER_UI_HOST: ${DOCKER_UI_HOST}
            VIRTUAL_HOST: api.wikiforest.com
    server:
        build:
            context: ./deploy/docker/
            dockerfile: Dockerfile.${DOCKER_SERVER_ENV}
        container_name: wiki_server_hyperf
        image: wikiforest/hyperf:${DOCKER_SERVER_IMAGE_TAB}
        entrypoint: ["php", "/opt/www/bin/hyperf.php", "start"]
        restart: always
        tty: true
        volumes:
            - .:/opt/www
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./deploy/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWD}
        expose:
            - ${DOCKER_DB_PORT}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.9.4-fpm-alpine
        restart: always
        environment:
            PMA_HOST: db
            PMA_VERBOSE: 8
            PMA_PORT: ${DOCKER_DB_PORT}
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWD}
        volumes:
            - ./deploy/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "2334:80"
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9000:9000"
        environment:
            VIRTUAL_HOST: container.wikiforest.com
