version: "3.7"
services:
    web:
        image: nginx:latest
        restart: always
        volumes:
            - ./deploy/nginx/templates:/etc/nginx/templates
            - ./deploy/nginx/logs:/web/logs/nginx
            - .:/opt/www
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
            - LOCAL_IP=${LOCAL_IP}
    server:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: wiki_server_hyperf
        image: alexlayton/hyperf:1.0.0
        restart: always
        volumes:
            - .:/opt/www
        expose:
            - "9501"
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./deploy/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: blldxt
        expose:
            - "3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_VERBOSE: 8
            PMA_PORT: 3306
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: blldxt
        ports:
            - "2334:80"
